# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugeereport',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.State'),
        ),
        migrations.AddField(
            model_name='refugeereport',
            name='state_count_total',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='refugeereport',
            name='city_count',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='refugeereport',
            name='state_count',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='refugeereport',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
